### ISSUE TITLE
no jvm 16 / jvm 17 version for latest release

### ISSUE THREAD

**Issue by cmdjulian** [paketo-buildpacks/eclipse-openj9#145]
Are there any reasons why you guys didn't include JVM 16 / 17 versions in the last release?

We are using Kotlin with JVM target 16. The last release broke our builds because the current version `8.7.0` doesn't come with a release for JVM 16 or above.  We therefore pinned the buildpack to the prior version `8.6.1` as a hotfix, which still includes JVM 16.  In the project README JVM 16 is still listed in the examples.
The liberica JVM offers now JVM 17, which would also be fine for us. But we wanna use openj9 JVM.

Any plans to support JVM 17 for this buildpack as well or bring back JVM 16?

Thanks in advance.

**Comment by dmikusa-pivotal** [comment]
Java 16 is out of general support. It's not getting patches anymore so we have removed that from the buildpacks. You could go back and use an older version of the buildpacks and Java 16 would be available, however, there are known CVEs against it, so that's not recommended.

Java 17 while out as a whole, does not seem to be available for OpenJ9. We used to pull our updates from AdoptOpenJDK for Eclipse OpenJ9, however, with that site shutting down and moving to Adoptium, they are no longer publishing Eclipse OpenJ9 builds. The builds are now coming from IBM Semeru and they have yet to publish a Java 17 build.

We're tracking this site for builds: https://developer.ibm.com/languages/java/semeru-runtimes/downloads

As soon as something is published, we'll pick it up.

If you have any tips on where we can get OpenJ9 builds from, I'd be happy to look into pulling builds from elsewhere. We don't do the builds ourselves though, so we can only provide what's available upstream.

**Comment by dmikusa-pivotal** [comment]
Upstream has released IBM Semeru Java 17. The latest eclipse-openj9 CNB has this support.
